name: 02_temperature_maps_2018
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python=3.8.*
  - pytorch=1.8.*
  - cudatoolkit
  - numpy
  - pandas
  - matplotlib
  - jupyter
  - pip
  - pip:
  	- 
