name: temperature_maps_2018

channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
  
dependencies:
  - python=3.9.4
  - pytorch=1.8.1
  - cudatoolkit=11.1
  - pip=21.0.1
  - pip:
     - -r requirements.txt
