name: aia_autocalibration_2019

channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults

dependencies:
  - python==3.9.4
  - pytorch=1.8.1
  - cudatoolkit=11.1
  - pip==21.0.1
  - sunpy==2.1.*
  - pip:
      - -r requirements.txt
      - -e sdo-autocal_pub/.

